### ISSUE TITLE
getMembersOfGroup does not pass all parameters to endpoint

### ISSUE THREAD

**Issue by tomcorke** [DestinyItemManager/bungie-api-ts#2]
Specifically: `currentpage` is a required property in `GetMembersOfGroupParams` but is not passed to the endpoint:

```
function getMembersOfGroup(http, params) {
    return http({
        method: 'GET',
        url: "https://www.bungie.net/Platform/GroupV2/" + params.groupId + "/Members/",
        params: {
            memberType: params.memberType,
            nameSearch: params.nameSearch
        }
    });
}
```

**Comment by bhollis** [comment]
Thanks for the report! We don’t use these endpoints in DIM, but a pull request to fix the generator would be appreciated.

**Comment by sundevour** [comment]
this goes for all of:
GetMembersOfGroup
GetAdminsAndFounderOfGroup
GetBannedMembersOfGroup
GetPendingMemberships
GetInvitedIndividuals

https://bungie-net.github.io/multi/operation_get_GroupV2-GetMembersOfGroup.html#operation_get_GroupV2-GetMembersOfGroup
as seen here :arrow_up:,
`currentpage` is a path parameter, but the spec does not say where to put it in the path
maybe i am missing something implied in bungie's docs?
