### ISSUE TITLE
`bungie-api-ts/common` is not exposed in the generated package.json's `exports` field

### ISSUE THREAD

**Issue by meyer** [DestinyItemManager/bungie-api-ts#39]
I’m trying to use `BungieMembershipType` from `bungie-api-ts/common` and webpack 5 is yelling at me:

> Module not found: Error: Package path ./common is not exported from package ./node_modules/bungie-api-ts (see exports field in ./node_modules/bungie-api-ts/package.json)

At the moment I’m digging around to see if I can override the exports field with a plugin. Worst case scenario: I’ll hard-code the enum value. Not the end of the world, but it’s not Technically Correct™.

_(Personal opinion: Given that 1. this module only exports ESM code and 2. the structure of the generated code perfectly matches what the exports field contains, the exports field can [again IMO] probably be omitted. One less thing to maintain!)_

Thank you for this fantastic package 🙏

**Comment by meyer** [comment]
Clean solution: I ended up setting [`exportsFields`](https://webpack.js.org/configuration/resolve/#resolveexportsfields) to an empty array.

**Comment by bhollis** [comment]
Unfortunately your opinion does not match with NodeJS' implementation!

`common` is reexported from the service-specific modules, so you can do this:

`import { BungieMembershipType } from 'bungie-api-ts/destiny2';`

**Comment by meyer** [comment]
Oh perfect, I forgot `/destiny2` was a thing. I’ve been relying on editor autocompletion.

**Comment by meyer** [comment]
Ha, I was about to close this but you beat me to it. Thanks for the speedy response!
